FROM registry.access.redhat.com/ubi9@sha256:ed84f34cd929ea6b0c247b6daef54dd79602804a32480a052951021caf429494

# Volumes:
#  * /var/lib/pgsql/data   - Database cluster for PostgreSQL.
# Environment:
#  * $POSTGRESQL_USER     - Database user name.
#  * $POSTGRESQL_PASSWORD - User's password.
#  * $POSTGRESQL_DATABASE - Name of the database to create.
#  * $POSTGRESQL_ADMIN_PASSWORD (Optional) - Password for the 'postgres' administrator user.

ENV POSTGRESQL_VERSION=16 \
    POSTGRESQL_PREV_VERSION=15 \
    PG_HOME=/var/lib/pgsql

EXPOSE 5432

RUN dnf -y module install "postgresql:${POSTGRESQL_VERSION}/server" && \
    INSTALL_PKGS="bind-utils gettext glibc-langpack-en glibc-locale-source nss_wrapper rsync tar" && \
    dnf install -y --allowerasing --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    postgres -V | grep -qe "$POSTGRESQL_VERSION\." && echo "Found VERSION $POSTGRESQL_VERSION" && \
    dnf -y clean all --enablerepo='*' && \
    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
    mkdir -p "${PG_HOME}"/data && \
    chgrp -R 0 "${PG_HOME}" /var/run/postgresql && chmod -R g=u "${PG_HOME}" /var/run/postgresql

ENV LANG=en_US.UTF-8 \
    CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/postgresql

COPY postgresql/source/usr /usr

ENTRYPOINT ["container-entrypoint"]
CMD ["run-postgresql"]